CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	SEXO ENUM ('M', 'F') NOT NULL,
	EMAIL VARCHAR(50)UNIQUE
);

create table endereco (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT, 
	FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);
	
/* ENDEREÇO - OBRIGATÓRIO 
CADASTRO SOMENTE UM.

TELEFONE - NÃO OBRIGATÓRIO 
CADASTRO DE MAIS UM (OPCIONAL)*/


INSERT INTO CLIENTE VALUES(NULL, 'JOAO', '27893742987','M','JOAO@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'ANA', '80923478798','F','ANA@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'ROBERTO', '23424234234','M','ROBERTO@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'CLAUDIA', '678945764456','F','CALUDIA@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'JULIA', '275893475','F','JULIA@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS', '3845739487345','M','CARLOS@GMAIL.COM');


CLIENTE
+-----------+---------+---------------+------+-------------------+
| IDCLIENTE | NOME    | CPF           | SEXO | EMAIL             |
+-----------+---------+---------------+------+-------------------+
|         1 | JOAO    | 27893742987   | M    | JOAO@GMAIL.COM    |
|         3 | ANA     | 80923478798   | F    | ANA@GMAIL.COM     |
|         4 | ROBERTO | 23424234234   | M    | ROBERTO@GMAIL.COM |
|         5 | CLAUDIA | 678945764456  | F    | CALUDIA@GMAIL.COM |
|         6 | JULIA   | 275893475     | F    | JULIA@GMAIL.COM   |
|         7 | CARLOS  | 3845739487345 | M    | CARLOS@GMAIL.COM  |
+-----------+---------+---------------+------+-------------------+


ENDEREÇO
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| IDENDERECO | int(11)     | NO   | PRI | NULL    | auto_increment |
| RUA        | varchar(50) | NO   |     | NULL    |                |
| CIDADE     | varchar(20) | NO   |     | NULL    |                |
| ESTADO     | char(2)     | NO   |     | NULL    |                |
| BAIRRO     | varchar(20) | NO   |     | NULL    |                |
| ID_CLIENTE | int(11)     | YES  | UNI | NULL    |                |
+------------+-------------+------+-----+---------+----------------+

TELEFONE
+------------+-------------------------+------+-----+---------+----------------+
| Field      | Type                    | Null | Key | Default | Extra          |
+------------+-------------------------+------+-----+---------+----------------+
| IDTELEFONE | int(11)                 | NO   | PRI | NULL    | auto_increment |
| TIPO       | enum('RES','COM','CEL') | NO   |     | NULL    |                |
| NUMERO     | varchar(10)             | NO   |     | NULL    |                |
| ID_CLIENTE | int(11)                 | YES  | MUL | NULL    |                |
+------------+-------------------------+------+-----+---------+----------------+

INSERT INTO endereco VALUES (NULL, 'RUA PAPAYA', 'SÃO PAULO', 'SP', 'VILA DOS REMEDIOS', 1);
INSERT INTO endereco VALUES (NULL, 'RUA LARANJA', 'OSASCO', 'SP', 'VIL DOS ABACATES', 3);
INSERT INTO endereco VALUES (NULL, 'RUA ABACATE', 'COTIA', 'SP', 'MELANCIA', 4);
INSERT INTO endereco VALUES (NULL, 'RUA MANGA', 'SÃO PAULO', 'SP', 'BELA VISTA', 5);
INSERT INTO endereco VALUES (NULL, 'RUA UVA', 'CARAPICUIBA', 'SP', 'VELOSO', 6);
INSERT INTO endereco VALUES (NULL, 'RUA LIMÃO', 'BARUERI', 'SP', 'LAPA', 7);


INSERT INTO TELEFONE VALUES(NULL, 'RES', '98323478', 1);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '789459847', 3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '1198567987', 7);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '7634876827', 1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '893457598', 3);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '5379537238', 7);


/*SELEÇÃO, PROJEÇÃO E JUNÇÃO */

/* PROJEÇÃO = TUDO QUE SE VÊ NA TELA */

SELECT NOW() AS DATA_ATUAL;

SELECT 2+2 AS SOMA;

SELECT 2+2 AS SOMA, NOME, NOW()
FROM CLIENTE;


/* SELEÇÃO = SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA 
A CLAUSULA DE SELEÇÃO É O WHERE */
 

SELECT NOME, SEXO, EMAIL /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELEÇÃO */

SELECT NUMERO   /* PROJEÇÃO */  
FROM TELEFONE  /* ORIGEM */  
WHERE TIPO = 'CEL';  /* SELEÇÃO */  


/* JUNÇÃO - JOIN */  

SELECT NOME, SEXO, RUA, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO 
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE 
ON IDCLIENTE = ID_CLIENTE
ORDER BY NOME;


SELECT A.NOME, A.SEXO, B.BAIRRO, B.CIDADE, C.TIPO, C.NUMERO
FROM CLIENTE A
INNER JOIN ENDERECO B
ON A.IDCLIENTE = B.ID_CLIENTE
INNER JOIN TELEFONE C 
ON A.IDCLIENTE = C.ID_CLIENTE
ORDER BY A.NOME;


/*
   		DML - DATA MANIPULATION LANGUAGE
   		DDL - DATA DEFINITION LANGUAGE 
   		DCL - DATA CONTROL LANGUAGE 
   		TCL - TRANSACTION CONTROL LANGUAGE 
*/


 /* DML */ 

/* INSERT */

INSERT INTO CLIENTE VALUES(NULL,'PAULA','3475347534', 'M', NULL);
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ',7);

SELECT * FROM CLIENTE;

/* FILTROS */

SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/* UPDATE */

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 8;

/* DELETE */ 

INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 8;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PORDUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);

ALTER TABLE PRODUTO 
CHANGE VALOR_UNITARIO VALOR FLOAT(10,2)NOT NULL;

ALTER TABLE PRODUTO
ADD PESO FLOAT(5,2) NOT NULL;

ALTER TABLE PRODUTO
DROP COLUMN PESO;

ALTER TABLE PRODUTO
ADD PESO FLOAT(5,2)
AFTER NOME_PORDUTO;

ALTER TABLE PRODUTO
ADD PESO FLOAT(5,2)
AFTER VALOR;

SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE
WHERE SEXO = 'M';


SELECT COUNT(*) NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

+------+------+
| NOME | SEXO |
+------+------+
|    9 | M    |
+------+------+

SELECT COUNT(*) NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

+------+------+
| NOME | SEXO |
+------+------+
|   11 | F    |
+------+------+


SELECT A.IDCLIENTE, A.EMAIL, A.NOME, A.SEXO, C.TIPO
FROM CLIENTE A
INNER JOIN ENDERECO B
ON = A.IDCLIENTE = B.ID_CLIENTE 
INNER JOIN TELEFONE C
ON A.IDCLIENTE = C.ID_CLIENTE
WHERE A.SEXO = 'F' 
AND B.BAIRRO = 'CENTRO' 
AND B.CIDADE = 'RIO DE JANEIRO' ;

SELECT A.IDCLIENTE, A.EMAIL, A.NOME, A.SEXO, C.TIPO, B.BAIRRO, B.CIDADE
FROM CLIENTE A
INNER JOIN ENDERECO B
ON A.IDCLIENTE = B.ID_CLIENTE
INNER JOIN TELEFONE C 
ON A.IDCLIENTE = C.ID_CLIENTE
WHERE A.SEXO = 'F'
AND B.BAIRRO = 'CENTRO' AND B.CIDADE = 'RIO DE JANEIRO';



SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO';

UPDATE  CLIENTE 
SET SEXO = 'M'
WHERE IDCLIENTE = 15;

SELECT C.NOME, C.NOME, T.NUMERO AS CELULAR
FROM CLIENTE C INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE 
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';


SELECT C.NOME, 
	   IFNULL(C.EMAIL, 'VAZIO'), 
	   E.ESTADO, 
	   T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/* VIEW */
CREATE VIEW  V_RELATORIO AS
SELECT C.NOME,
       C.SEXO,
       IFNULL(C.EMAIL, 'CLIENTE SEM EMAIL') AS 'EMAIL',
       T.TIPO,
       T.NUMERO,
       E.BAIRRO,
       E.CIDADE,
       E.ESTADO 
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT *FROM RELATORIO;

/* PARA VER AS VIEWS DENTRO DO SHOW TABLES */
/* SEPARAR O NOME DAS VIEWS PQ ELAS SE MISTURAM AO MEIO DAS TABLES */

DROP VIEW RELATORIO;

SHOW TABLES;

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;

/* É PERMITIDO FAZER UPDATES EM VIEWS COM JOIN */
/* NÃO É PERMITDO ALTERAR E DELETAR POR VIEW */

/*ORDER BY */

SELECT * FROM ALUNOS 
ORDER BY NOME;
