CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CARROS (
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	ID_MARCA INT,
	MODELO VARCHAR (15) NOT NULL	
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CARRO INT UNIQUE,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE COR (
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	NOMECOR VARCHAR(15)
);

CREATE TABLE TELEFONE ( 
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT, 
	TIPO CHAR (3) NOT NULL,
	NUMERO VARCHAR (11) NOT NULL
);

CREATE TABLE MARCA ( 
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	ID_CARRO INT UNIQUE, 
	MARCA VARCHAR(15) UNIQUE
);

CREATE TABLE RELACAO_CARRO_COR(
	ID_COR INT , 
	ID_CARRO INT,
	PRIMARY KEY (ID_COR, ID_CARRO)
);


ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CARRO_CLIENTE
FOREIGN KEY (ID_CARRO)
REFERENCES CARROS (IDCARRO);

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) 
REFERENCES CLIENTE (IDCLIENTE);

ALTER TABLE CARROS
ADD CONSTRAINT FK_MARCA_CARRO
FOREIGN KEY (ID_MARCA) 
REFERENCES MARCA (IDMARCA);

ALTER TABLE RELACAO_CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES COR(IDCOR);

ALTER TABLE RELACAO_CARRO_COR 
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR)
REFERENCES CARROS(IDCARRO); 


INSERT INTO MARCA (MARCA) VALUES ('Toyota');
INSERT INTO MARCA (MARCA) VALUES ('Honda');
INSERT INTO MARCA (MARCA) VALUES ('Ford');

INSERT INTO CARROS (ID_MARCA, MODELO) VALUES (1, 'Corolla');
INSERT INTO CARROS (ID_MARCA, MODELO) VALUES (2, 'Civic');
INSERT INTO CARROS (ID_MARCA, MODELO) VALUES (3, 'Mustang');

INSERT INTO CLIENTE (ID_CARRO, NOME) VALUES (1, 'Carlos Silva');
INSERT INTO CLIENTE (ID_CARRO, NOME) VALUES (2, 'Ana Maria');
INSERT INTO CLIENTE (ID_CARRO, NOME) VALUES (3, 'João Souza');

INSERT INTO COR (NOMECOR) VALUES ('Vermelho');
INSERT INTO COR (NOMECOR) VALUES ('Azul');
INSERT INTO COR (NOMECOR) VALUES ('Preto');

INSERT INTO TELEFONE (ID_CLIENTE, TIPO, NUMERO) VALUES (1, 'CEL', '99999999999');
INSERT INTO TELEFONE (ID_CLIENTE, TIPO, NUMERO) VALUES (2, 'RES', '88888888888');
INSERT INTO TELEFONE (ID_CLIENTE, TIPO, NUMERO) VALUES (3, 'COM', '77777777777');

INSERT INTO RELACAO_CARRO_COR (ID_COR, ID_CARRO) VALUES (1, 1);
INSERT INTO RELACAO_CARRO_COR (ID_COR, ID_CARRO) VALUES (2, 2);
INSERT INTO RELACAO_CARRO_COR (ID_COR, ID_CARRO) VALUES (3, 3);